Repository scrum-gang/resume-revision, pull requests merged in 2019-03, with the labels that each got.

#25 Add authentication and authorization
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/resumes_controller.rb
  app/service/authentication_token_verifier.rb
  config/routes.rb
  test/controllers/resume_controller_test.rb
Labels: Enhancement

#27 Finishing the tests for the application
  Gemfile
  Gemfile.lock
  app/controllers/resumes_controller.rb
  test/controllers/resume_controller_test.rb
  test/controllers/resumes_controller_auth_test.rb
  test/controllers/resumes_controller_test.rb
  test/models/resume_test.rb
  test/services/authentication_token_verifier_test.rb
Labels: Bug, tests

#28 Added code coverage using SimpleCov
  .gitignore
  .travis.yml
  Gemfile
  Gemfile.lock
  test/controllers/.keep
  test/controllers/resumes_controller_auth_test.rb
  test/controllers/resumes_controller_test.rb
  test/fixtures/.keep
  test/models/.keep
  test/models/resume_test.rb
  test/services/authentication_token_verifier_test.rb
  test/test_helper.rb
Labels: Enhancement

#30 Authentication URL from production to staging
  app/service/authentication_token_verifier.rb
Labels: Bug
