Repository scrum-gang/resume-revision, pull requests merged in 2019-02, with the labels that each got.

#12 Setup up Travis CI
  .gitignore
  .ruby-version
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/resumes_controller.rb
  app/models/resume.rb
  config/application.rb
  config/credentials.yml.enc
  config/database.yml
  config/routes.rb
  config/storage.yml
  db/migrate/20190203204636_create_active_storage_tables.rb
  db/migrate/20190204233345_create_resume_table.rb
  package.json
  test/application_system_test_case.rb
  test/integration/.keep
  test/mailers/.keep
  test/system/.keep
Labels: Setup

#13 Add Listing functionalities for Resumes
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/application_controller.rb
  app/controllers/resumes_controller.rb
  app/models/resume.rb
  config/routes.rb
  db/migrate/20190204233345_create_resume_table.rb
  test/assets/sample_resume.txt
  test/controllers/resume_controller_test.rb
  test/fixtures/resumes.yml
  test/models/resume_test.rb
  test/test_helper.rb
Labels: Enhancement, Feature

#15 Delete and update resume
  README.md
  app/controllers/resumes_controller.rb
  app/models/resume.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/routes.rb
  db/migrate/20190204233345_create_resume_table.rb
  db/migrate/20190209204755_add_resume_download_url.rb
  db/migrate/20190209210059_change_user_id_to_string.rb
  db/schema.rb
  test/controllers/resume_controller_test.rb
  test/fixtures/resumes.yml
Labels: Enhancement, Feature, Setup

#17 Add azure active storage to the project
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/environments/test.rb
  config/storage.yml
Labels: Bug, DB, Enhancement

#18 Cleanup + Linting + Refactoring
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/controllers/resumes_controller.rb
  app/mailers/application_mailer.rb
  app/models/resume.rb
  app/views/layouts/application.html.erb
  app/views/layouts/mailer.html.erb
  config/database.yml
  config/routes.rb
  test/controllers/resume_controller_test.rb
  test/fixtures/resumes.yml
  test/models/resume_test.rb
  test/test_helper.rb
Labels: Enhancement
